"use client";

import type { Metadata } from "next";
import theSeasonsFont from "next/font/local";
import centuryGothicFont from "next/font/local";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Image from "next/image";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ModeToggle } from "@/components/ModeToggle";
import { usePathname } from "next/navigation";

const theSeasons = theSeasonsFont({
  src: [
    {
      path: "./fonts/The_Seasons/theseasons-lt.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/The_Seasons/theseasons-ltit.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/The_Seasons/theseasons-reg.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/The_Seasons/theseasons-it.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/The_Seasons/theseasons-bd.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/The_Seasons/theseasons-bdit.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-the-seasons",
});

const centuryGothic = centuryGothicFont({
  src: [
    {
      path: "./fonts/Century_Gothic/centurygothic.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Century_Gothic/centurygothic_bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-century-gothic",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-open-sans",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  const hideRootShell =
    pathname === "/login" || pathname?.startsWith("/login/");

  return (
    <html
      lang="en"
      className={`${theSeasons.variable} ${centuryGothic.variable} ${openSans.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased min-h-screen flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {!hideRootShell && (
            <header>
              <div className="flex items-center justify-between w-full px-4">
                <div></div>

                <div className="flex items-center gap-4">
                  <Image
                    src="/logo.svg"
                    alt="Limited Watches Logo"
                    width={80}
                    height={80}
                  />
                  <h1 className="text-3xl font-seasons font-semibold text-champagne">
                    Limited Watches
                  </h1>
                </div>

                <div className="w-20 flex justify-end">
                  <ModeToggle />
                </div>
              </div>
            </header>
          )}

          {!hideRootShell && (
            <nav className="container mx-auto">
              <Navbar />
            </nav>
          )}

          {/* main content area */}
          {hideRootShell ? (
            // For the auth page (login) we want the page to take full height
            // and not show the navbar and footer.
            <div className="min-h-screen w-full">{children}</div>
          ) : (
            <main className="container mx-auto flex-1 pt-5 pb-5">
              {children}
            </main>
          )}

          {!hideRootShell && <Footer />}
        </ThemeProvider>
      </body>
    </html>
  );
}
