"use client";

import theSeasonsFont from "next/font/local";
import centuryGothicFont from "next/font/local";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Logo from "@/components/Logo";
import { Navbar } from "@/components/Navbar/Navbar";
import { Footer } from "@/components/Footer";
import { ModeToggle } from "@/components/Navbar/ModeToggle";
import { usePathname, redirect } from "next/navigation";
import {} from "react";
import { ChatProvider, useChatContext } from "@/context/ChatContext";
import { FloatingChatButton } from "@/components/Chat/FloatingChatButton";
import { ChatPanel } from "@/components/Chat/ChatPanel";
import { X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AnimatePresence, motion } from "framer-motion";
import ChatBox from "@/components/Chat/ChatBox";
import { useSupabaseAuth } from "@/hooks/useSupabaseAuth";
import { Toaster } from "sonner";

const theSeasons = theSeasonsFont({
  src: [
    {
      path: "./fonts/The_Seasons/theseasons-lt.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/The_Seasons/theseasons-ltit.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/The_Seasons/theseasons-reg.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/The_Seasons/theseasons-it.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/The_Seasons/theseasons-bd.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/The_Seasons/theseasons-bdit.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-the-seasons",
});

const centuryGothic = centuryGothicFont({
  src: [
    {
      path: "./fonts/Century_Gothic/centurygothic.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Century_Gothic/centurygothic_bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-century-gothic",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-open-sans",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideRootShell =
    pathname === "/login" ||
    pathname?.startsWith("/admin") ||
    pathname?.startsWith("/login/");

  // chat state is provided by ChatProvider via context

  return (
    <html
      lang="en"
      className={`${theSeasons.variable} ${centuryGothic.variable} ${openSans.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased min-h-screen flex flex-col">
        <ChatProvider>
          <Toaster />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {!hideRootShell && (
              <nav className="container mx-auto">
                <header>
                  <div className="flex items-center justify-between w-full px-4">
                    <div></div>
                    <div className="pt-4 pb-4">
                      <div
                        onClick={() => redirect("/")}
                        className="flex flex-col items-center justify-center gap-2 cursor-pointer"
                      >
                        <div className="">
                          <Logo className="h-12 w-12 dark:text-white" />
                        </div>
                        <h1 className="text-2xl font-bold">Limited Watches</h1>
                      </div>
                    </div>

                    <div className="w-20 flex justify-end">
                      <ModeToggle />
                    </div>
                  </div>
                </header>
                <Navbar />
              </nav>
            )}

            {/* main content area */}
            {hideRootShell ? (
              // For the auth page (login) we want the page to take full height
              // and not show the navbar and footer.
              <div className="min-h-screen w-full">{children}</div>
            ) : (
              <main className="min-h-screen pt-5 pb-5">{children}</main>
            )}

            {!hideRootShell && <Footer />}

            {/* Floating chat button + panel (visible on all non-admin/login pages) */}
            {!hideRootShell && <LayoutChatControls />}
          </ThemeProvider>
        </ChatProvider>
        <Toaster />
      </body>
    </html>
  );
}

function LayoutChatControls() {
  const { chatOpen, setChatOpen, initialConversation, setInitialConversation } =
    useChatContext();

  return (
    <>
      <FloatingChatButton
        onClick={() => setChatOpen((s) => !s)}
        open={chatOpen}
      />

      {chatOpen && (
        <AnimatePresence>
          <ChatBox
            setChatOpen={setChatOpen}
            initialConversation={initialConversation}
            setInitialConversation={setInitialConversation}
          />
        </AnimatePresence>
      )}
    </>
  );
}
