name: Build and push Docker image to GitHub Container Registry then deploy on self-hosted server

on:
    push:
        branches: [ "main", "dev" ]
        tags: ["v*"] # when we tag the repository with a version like v1.0.0 in main to create releases
    workflow_dispatch:

jobs:
    migrate-dev:
        if: github.ref == 'refs/heads/dev'
        uses: ./.github/workflows/migrations.yml
        with:
            environment: "dev"
            node-version: "24"
            npm-script: "db:migrate:dev"
        secrets:
            database-url: ${{ secrets.DATABASE_URL_DEV }}
  
    migrate-prod:
        if: github.ref == 'refs/heads/main'
        uses: ./.github/workflows/migrations.yml
        with:
            environment: "prod"
            node-version: "24"
            npm-script: "db:migrate:prod"
        secrets:
            database-url: ${{ secrets.DATABASE_URL_PROD }}






    build-and-push:
        needs: [migrate-dev, migrate-prod]
        if: always() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
        runs-on: blacksmith-4vcpu-ubuntu-2404

        permissions:
            contents: read
            packages: write

        steps:
            - name: Fail if migration failed
              if: needs.migrate-dev.result == 'failure' || needs.migrate-prod.result == 'failure'
              run: |
                echo "Migration failed — aborting pipeline."
                exit 1

            - name: Checkout repository
              uses: actions/checkout@v4

            # Add Blacksmith cache here
            - name: Cache Docker layers
              uses: actions/cache@v4
              with:
                path: /tmp/.buildx-cache
                key: ${{ runner.os }}-buildx-${{ github.sha }}
                restore-keys: |
                  ${{ runner.os }}-buildx-

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: useblacksmith/setup-docker-builder@v1 # docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: (Dev) Build and push image (with registry cache)
              if: github.ref == 'refs/heads/dev'
              uses: useblacksmith/build-push-action@v2 # docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                platforms: linux/amd64
                push: true
                tags: |
                    ghcr.io/thaye-software/limited-watches-dev:latest
                    ghcr.io/thaye-software/limited-watches-dev:${{ github.sha }}
                # cache-from: type=registry,ref=ghcr.io/thaye-software/limited-watches-dev:cache
                # cache-to: type=registry,mode=max,ref=ghcr.io/thaye-software/limited-watches-dev:cache
                secrets: |
                    app_env=dev
                    database_url_dev=${{ secrets.DATABASE_URL_DEV }}
                    supabase_url=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
                    supabase_key=${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
                    stripe_secret_key=${{ secrets.STRIPE_SECRET_KEY}}
                    stripe_public_key=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}
                    resend_key=${{ secrets.RESEND_API_KEY}}
                    resend_origin_email_key=${{ secrets.RESEND_ORIGIN_EMAIL }}
                    posthog_key=${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
                    posthog_host=${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}


            - name: (Prod) Build and push image (with registry cache)
              if: github.ref == 'refs/heads/main'
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                platforms: linux/amd64
                push: true
                tags: |
                    ghcr.io/thaye-software/limited-watches-prod:latest
                    ghcr.io/thaye-software/limited-watches-prod:${{ github.sha }}
                cache-from: type=registry,ref=ghcr.io/thaye-software/limited-watches-prod:cache
                cache-to: type=registry,mode=max,ref=ghcr.io/thaye-software/limited-watches-prod:cache
                secrets: |
                    app_env=prod
                    database_url_prod=${{ secrets.DATABASE_URL_PROD }}
                    supabase_url=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
                    supabase_key=${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}

    deploy:
        needs: build-and-push
        if: always() && needs.build-and-push.result == 'success'
        runs-on: blacksmith-2vcpu-ubuntu-2404
        steps:

            - name: Setup SSH Key
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
                chmod 600 ~/.ssh/deploy_key
            
            - name: Add Known Hosts
              run: |
                ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: (Dev) Deploy to Server
              if: github.ref == 'refs/heads/dev'
              run: |
                ssh -t -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
                  set -e
                  echo "${{ secrets.GHCR_ACCESS_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                  cd limited-watches/dev/
                  docker compose up -d --pull always --remove-orphans
                  docker image prune -af --filter "until=24h"
                  echo "Deployment to development completed."
                EOF

            - name: (Prod) Deploy to Server
              if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
              run: |
                ssh -t -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
                  set -e
                  echo "${{ secrets.GHCR_ACCESS_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                  cd limited-watches/prod/
                  docker compose up -d --pull always --remove-orphans
                  docker image prune -af --filter "until=24h"
                  echo "Deployment to production completed."
                EOF
