name: (CronJob) Release Expired Order Reservations

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # runs every 30 minutes

jobs:
  scheduled-cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Call endpoint releasing reserved orders
        run: |
          curl -X PATCH \
            -H "x-limitedwatches-secret: ${{ secrets.LIMITED_WATCHES_WEBHOOK_SECRET }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.LIMITED_WATCHES_EXPIRED_ORDERS_WEBHOOK_URL }}"
